hostname = filecdn-other.xingyeai.com, www.minebbs.com

^https:\/\/filecdn-other\.xingyeai\.com\/xingye_operation\/image\/\d+_\d+_\.png$ url reject-img
^https:\/\/www\.minebbs\.com\/data\/siropu\/am\/user\/[a-f0-9]+\.webp url reject-img