hostname = filecdn-other.xingyeai.com, www.minebbs.com, api.xingyeai.com, www.tucao.my

^https:\/\/filecdn-other\.xingyeai\.com\/xingye_operation\/image\/\d+_\d+_\.png$ url reject-img
^https:\/\/www\.minebbs\.com\/data\/siropu\/am\/user\/[a-f0-9]+\.webp url reject-img
^https:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/payment\/get_pop_info\?[^\s]+$ url reject-200
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/ad\/get_draw_gem_progress url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyads.js
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/feed\/get_feed_tab url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyads2.js
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/user\/get_user_settings url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyads3.js
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/settings\/get_app_settings url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyads4.js
https?://www\.tucao\.my/uploadfile/\d{4}/\d{4}/[^?]+\.(?:jpg|gif)\?Sat url reject-img