hostname = filecdn-other.xingyeai.com, www.minebbs.com, api.xingyeai.com

^https:\/\/filecdn-other\.xingyeai\.com\/xingye_operation\/image\/\d+_\d+_\.png$ url reject-img
^https:\/\/www\.minebbs\.com\/data\/siropu\/am\/user\/[a-f0-9]+\.webp url reject-img
^https:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/payment\/get_pop_info\?[^\s]+$ url reject-200
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/ad\/get_draw_gem_progress url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyads.js
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/feed\/get_feed_tab url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyads2.js
