hostname = api.xingyeai.com,filecdn-other.xingyeai.com

^https:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/payment\/get_pop_info url reject-dict
^https?:\/\/filecdn-other\.xingyeai\.com\/xingye_operation\/image\/ url reject-img
^https:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/payment\/subscription\/list_v2 url reject-dict

