hostname = api.xingyeai.com,mirror.xingyeai.com,relay-event.xingyeai.com,meerkat-prod.xaminim.com

^https?:\/\/meerkat-prod\.xaminim\.com\/meerkat-reporter\/api\/report url reject-200
^https?:\/\/mirror\.xingyeai\.com\/mirror\/distribution\/api\/v1\/report url reject-200
^https?:\/\/relay-event\.xingyeai\.com\/api\/7\/envelope\/ url reject-200
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/ad\/get_ad_data url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyad.js
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/ad\/get_app_splash url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyad.js
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/ad\/get_draw_gem_progress url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyad.js
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/payment\/get_pop_info url script-response-body https://raw.githubusercontent.com/zbzxbg/Qx-Loon-Shad/refs/heads/main/xyad.js
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/ad\/report_ad_rt_events url reject-200
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/user\/report_app_list url reject-200