hostname = api.xingyeai.com,filecdn-other.xingyeai.com

^https?:\/\/filecdn-other\.xingyeai\.com\/xingye_operation\/image\/ url reject-img
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/payment\/get_pop_info url jsonjq-response-body del(.banner_item)
^https?:\/\/api\.xingyeai\.com\/weaver\/api\/v1\/payment\/subscription\/list_v2 url jsonjq-response-body del(.products, .products_by_vip_type)